name: grupchat
description: "The grup chat project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  build_runner: ^2.4.9
  card_loading: ^0.3.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.16.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  firebase_storage: ^11.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  loading_animation_widget: ^1.2.1
  logger: ^2.2.0
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  step_progress_indicator: ^1.0.2
  supabase_flutter: ^2.5.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/logos/
    - assets/icons/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/large_logo.png
  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/logos/large_logo.png
    android: true
    ios: true

  web: false
