// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOFdiY9F5yhSpfqWI0JB1Ie1AvybgAs8c',
    appId: '1:230303828815:web:0ee0b5ce9f003ed8b5933a',
    messagingSenderId: '230303828815',
    projectId: 'grupchat-io',
    authDomain: 'grupchat-io.firebaseapp.com',
    storageBucket: 'grupchat-io.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIiDlmpBMiXMR9lA4iMJ-zYAMCWn8exSc',
    appId: '1:230303828815:android:db7c97d72d98154eb5933a',
    messagingSenderId: '230303828815',
    projectId: 'grupchat-io',
    storageBucket: 'grupchat-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvSVLr2ssZWdkFYnVrxKH00uQhf0G1do',
    appId: '1:230303828815:ios:31ba16694580b5a5b5933a',
    messagingSenderId: '230303828815',
    projectId: 'grupchat-io',
    storageBucket: 'grupchat-io.appspot.com',
    iosBundleId: 'com.example.grupchatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkvSVLr2ssZWdkFYnVrxKH00uQhf0G1do',
    appId: '1:230303828815:ios:31ba16694580b5a5b5933a',
    messagingSenderId: '230303828815',
    projectId: 'grupchat-io',
    storageBucket: 'grupchat-io.appspot.com',
    iosBundleId: 'com.example.grupchatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOFdiY9F5yhSpfqWI0JB1Ie1AvybgAs8c',
    appId: '1:230303828815:web:a411b3e53ffe0587b5933a',
    messagingSenderId: '230303828815',
    projectId: 'grupchat-io',
    authDomain: 'grupchat-io.firebaseapp.com',
    storageBucket: 'grupchat-io.appspot.com',
  );
}
